FROM php:8.2-apache

#env vars for docker image
ENV FOLDER_BASE=/var/www/html

ENV APACHE_EXPOSE=80 \
    APACHE_RUN_USER=www-data \
    APACHE_RUN_USER_UID=1001 \
    APACHE_DOCUMENT_ROOT=${FOLDER_BASE} \
    APACHE_SERVER_NAME=localhost

# install the PHP extensions we need
RUN set -eux; \
	\
	if command -v a2enmod; then \
		a2enmod rewrite; \
	fi; \
	\
	savedAptMark="$(apt-mark showmanual)"; \
	\
	apt-get update; \
	apt-get install -y --no-install-recommends \
		libfreetype6-dev \
		libjpeg-dev \
		libpng-dev \
		libpq-dev \
		libwebp-dev \
		libzip-dev \
		curl \
	; \
	\
	docker-php-ext-configure gd \
		--with-freetype \
		--with-jpeg=/usr \
		--with-webp \
	; \
	\
	docker-php-ext-install -j "$(nproc)" \
		gd \
		opcache \
		pdo_mysql \
		zip \
	; \
	\
# reset apt-mark's "manual" list so that "purge --auto-remove" will remove all build dependencies
	apt-mark auto '.*' > /dev/null; \
	apt-mark manual $savedAptMark; \
	ldd "$(php -r 'echo ini_get("extension_dir");')"/*.so \
		| awk '/=>/ { print $3 }' \
		| sort -u \
		| xargs -r dpkg-query -S \
		| cut -d: -f1 \
		| sort -u \
		| xargs -rt apt-mark manual; \
	\
	apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
	rm -rf /var/lib/apt/lists/*

RUN pecl install redis \
    && docker-php-ext-enable redis \
    && apt-get clean

RUN mkdir -pm 777 ${APACHE_DOCUMENT_ROOT}

# Change apache settings (port, document_root, ServerName)
RUN sed -s -i -e "s/80/${APACHE_EXPOSE}/" /etc/apache2/ports.conf /etc/apache2/sites-available/*.conf && \
    sed -ri -e "s!/var/www/html!${APACHE_DOCUMENT_ROOT}!g" /etc/apache2/sites-available/*.conf && \
    sed -ri -e "s!/var/www/html!${APACHE_DOCUMENT_ROOT}!g" /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf && \
    echo "ServerName ${APACHE_SERVER_NAME}" >> /etc/apache2/apache2.conf

# set recommended PHP.ini settings
# see https://secure.php.net/manual/en/opcache.installation.php
RUN { \
		echo 'opcache.memory_consumption=128'; \
		echo 'opcache.interned_strings_buffer=8'; \
		echo 'opcache.max_accelerated_files=4000'; \
		echo 'opcache.revalidate_freq=60'; \
	} > /usr/local/etc/php/conf.d/opcache-recommended.ini

# set limits for PHP.ini settings
RUN { \
		echo 'memory_limit=2024M'; \
		echo 'upload_max_filesize=200M'; \
		echo 'post_max_size=200M'; \
	} > /usr/local/etc/php/conf.d/php-custom.ini

# Copy repository files
COPY ./www ${APACHE_DOCUMENT_ROOT}/

USER $APACHE_RUN_USER_UID

EXPOSE $APACHE_EXPOSE